export type PropertyType =
  | "Terrace"
  | "Condo/Apartment"
  | "Semi-D/Bungalow"
  | "Commercial"
  | "Land";

export interface Property {
  id: string;
  title: string;
  address: string;
  postcode: string;
  state: string;
  area: string;
  reservePrice: number;
  auctionDate: string;
  landArea: string;
  builtUp: string;
  tenure: "Freehold" | "Leasehold";
  type: PropertyType;
  image: string;
}

export const PROPERTIES: Property[] = [
  {
    "id": "2",
    "title": "Town House (Upper Unit)",
    "address": "No. 26-1, Jalan TTP 3, Taman Tasik Puchong, 47120 Puchong, Selangor",
    "postcode": "47120",
    "state": "Selangor",
    "area": "Puchong",
    "reservePrice": 198288,
    "auctionDate": "1 Jul 2026 (Wed)",
    "landArea": "—",
    "builtUp": "872 sq.ft",
    "tenure": "Freehold",
    "type": "Terrace",
    "image": "https://drive.google.com/thumbnail?id=1DpkeKtH1hRBseV5wTU2Sj8qCL-kK1IJu&sz=w800"
  },
  {
    "id": "4",
    "title": "Service Apartment",
    "address": "Unit No. A-08-18, Block A, Kiara Plaza, Jalan Semenyih, 43500 Semenyih, Selangor",
    "postcode": "43500",
    "state": "Selangor",
    "area": "Semenyih",
    "reservePrice": 216000,
    "auctionDate": "1 Jul 2026 (Wed)",
    "landArea": "—",
    "builtUp": "861 sq.ft",
    "tenure": "Freehold",
    "type": "Condo/Apartment",
    "image": "https://drive.google.com/thumbnail?id=1M-Qg5BJ52E_--kKxvXKUFFpFDeFQsB1Q&sz=w800"
  },
  {
    "id": "6",
    "title": "Condominium",
    "address": "Unit No. 02-03, Oasis 2, Jalan Mutiara 3, Mutiara Heights, 43000 Kajang, Selangor",
    "postcode": "43000",
    "state": "Selangor",
    "area": "Kajang",
    "reservePrice": 380000,
    "auctionDate": "1 Jul 2026 (Wed)",
    "landArea": "—",
    "builtUp": "250 sq.ft",
    "tenure": "Freehold",
    "type": "Condo/Apartment",
    "image": "https://drive.google.com/thumbnail?id=1qQEr6Jyc9bsPAKUmomaGDdUeo9XVScLk&sz=w800"
  },
  {
    "id": "7",
    "title": "Apartment",
    "address": "Unit No. P-111, Block P, Apartment Harmoni, No. 55, Jalan PJU 10/4C, Damansara Damai, 47830 Petaling Jaya, Selangor",
    "postcode": "47830",
    "state": "Selangor",
    "area": "Petaling Jaya",
    "reservePrice": 130000,
    "auctionDate": "1 Jul 2026 (Wed)",
    "landArea": "—",
    "builtUp": "650 sq.ft",
    "tenure": "Freehold",
    "type": "Condo/Apartment",
    "image": "https://drive.google.com/thumbnail?id=1jLqp9uDCtZa1TBfZtkcy_Yx4kTPMJ4BE&sz=w800"
  },
  {
    "id": "8",
    "title": "Service Apartment",
    "address": "Unit No. C-15-13, Block C, Mutiara Ville, Persiaran Sepang, Cyber 11, 63000 Cyberjaya, Selangor",
    "postcode": "63000",
    "state": "Selangor",
    "area": "Cyberjaya",
    "reservePrice": 350000,
    "auctionDate": "1 Jul 2026 (Wed)",
    "landArea": "—",
    "builtUp": "180 sq.ft",
    "tenure": "Freehold",
    "type": "Condo/Apartment",
    "image": "https://drive.google.com/thumbnail?id=1Np6uGfZzW5mfeUp-liptXAjwgdPh5BIA&sz=w800"
  },
  {
    "id": "9",
    "title": "Office Unit",
    "address": "Unit No. 2-9-3, Space U8, No. 6, Persiaran Pasak Bumi, Taman Bukit Jelutong, 40150 Shah Alam, Selangor",
    "postcode": "40150",
    "state": "Selangor",
    "area": "Shah Alam",
    "reservePrice": 380000,
    "auctionDate": "1 Jul 2026 (Wed)",
    "landArea": "—",
    "builtUp": "250 sq.ft",
    "tenure": "Freehold",
    "type": "Commercial",
    "image": "https://drive.google.com/thumbnail?id=12QRHBHpuB5vwKfF-VnTTatwOpjzgF6Bg&sz=w800"
  },
  {
    "id": "10",
    "title": "2 Storey Terrace House",
    "address": "No. 46, Jalan Ritma 2/5, Ritma Perdana, LBS Alam Perdana, 42300 Bandar Puncak Alam, Selangor",
    "postcode": "42300",
    "state": "Selangor",
    "area": "Bandar Puncak Alam",
    "reservePrice": 450000,
    "auctionDate": "1 Jul 2026 (Wed)",
    "landArea": "—",
    "builtUp": "420 sq.ft",
    "tenure": "Freehold",
    "type": "Terrace",
    "image": "https://drive.google.com/thumbnail?id=1X5TKUkmSnIjGQeYZO8xsKP5T1prSr1OH&sz=w800"
  },
  {
    "id": "11",
    "title": "Shop Lot",
    "address": "Unit No. C-LG-3A, Sfera Residensi, Jalan Atmosphere Utama 1, Bandar Putra Permai, 43300 Seri Kembangan, Selangor",
    "postcode": "43300",
    "state": "Selangor",
    "area": "Seri Kembangan",
    "reservePrice": 664200,
    "auctionDate": "1 Jul 2026 (Wed)",
    "landArea": "—",
    "builtUp": "970 sq.ft",
    "tenure": "Freehold",
    "type": "Commercial",
    "image": "https://drive.google.com/thumbnail?id=1d_kfRcAXQRY8mtdkkVFFJ0PzqQJFEcnB&sz=w800"
  },
  {
    "id": "12",
    "title": "Apartment",
    "address": "Unit No. C-4-08, Blok Cahaya, Putra Laksamana, 68100 Batu Caves, Selangor",
    "postcode": "68100",
    "state": "Selangor",
    "area": "Batu Caves",
    "reservePrice": 71280,
    "auctionDate": "1 Jul 2026 (Wed)",
    "landArea": "—",
    "builtUp": "650 sq.ft",
    "tenure": "Freehold",
    "type": "Condo/Apartment",
    "image": "https://drive.google.com/thumbnail?id=1KFgETtps6YzeR4iS8vT9cLfTJD0Cfsfr&sz=w800"
  },
  {
    "id": "14",
    "title": "2 Storey Terrace House",
    "address": "No. 59, Jalan Ritma 1/9, Ritma Perdana, LBS Alam Perdana, 42300 Bandar Puncak Alam, Selangor",
    "postcode": "42300",
    "state": "Selangor",
    "area": "Bandar Puncak Alam",
    "reservePrice": 500000,
    "auctionDate": "1 Jul 2026 (Wed)",
    "landArea": "—",
    "builtUp": "420 sq.ft",
    "tenure": "Freehold",
    "type": "Terrace",
    "image": "https://drive.google.com/thumbnail?id=1X5TKUkmSnIjGQeYZO8xsKP5T1prSr1OH&sz=w800"
  },
  {
    "id": "15",
    "title": "Service Apartment",
    "address": "Unit No. A-23A-10, Block A, D'Erica Residences @ Residensi Hijauan Rimba, Jalan PJU 8/8B, Sentral Damansara, PJU 8, 47620 Petaling Jaya, Selangor",
    "postcode": "47620",
    "state": "Selangor",
    "area": "Petaling Jaya",
    "reservePrice": 650000,
    "auctionDate": "1 Jul 2026 (Wed)",
    "landArea": "—",
    "builtUp": "200 sq.ft",
    "tenure": "Freehold",
    "type": "Condo/Apartment",
    "image": "https://drive.google.com/thumbnail?id=13TR-W423UWwGa6_AJY-H6FHaXd0zx5yL&sz=w800"
  },
  {
    "id": "23",
    "title": "Apartment",
    "address": "Unit No. B3-15-06, 15th Floor, Block B3, Residensi PR1MA Alam Damai, Persiaran Bistari, Alam Damai, 56000, Kuala Lumpur",
    "postcode": "56000",
    "state": "Kuala Lumpur",
    "area": "Kuala Lumpur",
    "reservePrice": 320000,
    "auctionDate": "1 Jul 2026 (Wed)",
    "landArea": "—",
    "builtUp": "936 sq.ft",
    "tenure": "Freehold",
    "type": "Condo/Apartment",
    "image": "https://drive.google.com/thumbnail?id=1cVC8feyuqT6bv3Ox9QQj3N_olhUPIDJ2&sz=w800"
  },
  {
    "id": "26",
    "title": "[Tranquil retreat away from the hustle and bustle of city life] 3 Storey Detached House with Basement, Swimming Pool & Private Lift [7 min to Kota Permai Golf & Country Club, Gamuda Walk Mall & Giant Hypermarket Kemuning Utama]",
    "address": "No. 2, Mutiara 33, Jalan Kemuning 33/158B, Seksyen 33, Taman Kemuning Utama (Residence 33 @ Kota Kemuning), 40400 Shah Alam, Selangor",
    "postcode": "40400",
    "state": "Selangor",
    "area": "Shah Alam",
    "reservePrice": 1584000,
    "auctionDate": "2 Jul 2026 (Thu)",
    "landArea": "—",
    "builtUp": "808 sq.ft",
    "tenure": "Freehold",
    "type": "Terrace",
    "image": "https://drive.google.com/thumbnail?id=1h0DKLFM6m4xcKauyKxmFTV93gH2EojRl&sz=w800"
  },
  {
    "id": "27",
    "title": "Apartment",
    "address": "Unit No. A-L5-15, Block A, Bandar Baru Kundang, 48020 Rawang, Selangor",
    "postcode": "48020",
    "state": "Selangor",
    "area": "Rawang",
    "reservePrice": 81000,
    "auctionDate": "2 Jul 2026 (Thu)",
    "landArea": "—",
    "builtUp": "764 sq.ft",
    "tenure": "Freehold",
    "type": "Condo/Apartment",
    "image": "https://drive.google.com/thumbnail?id=14sciZ7oOTYOEKUGaVydyxv288rKrEO4I&sz=w800"
  },
  {
    "id": "28",
    "title": "2 Storey Terrace House",
    "address": "No. 54, Jalan TKP 1, Taman Kantan Permai, 43000 Kajang, Selangor",
    "postcode": "43000",
    "state": "Selangor",
    "area": "Kajang",
    "reservePrice": 306000,
    "auctionDate": "2 Jul 2026 (Thu)",
    "landArea": "—",
    "builtUp": "976 sq.ft",
    "tenure": "Freehold",
    "type": "Terrace",
    "image": "https://drive.google.com/thumbnail?id=1PIDq0xxYxxkBoCHoYrrU6mQooCePCsg_&sz=w800"
  },
  {
    "id": "29",
    "title": "Apartment",
    "address": "Unit No. 9-4-30, Block 30, Pangsapuri Seroja, No. 2, Jalan Arca U8/80, Taman Bukit Jelutong, Seksyen U8, 40150 Shah Alam, Selangor",
    "postcode": "40150",
    "state": "Selangor",
    "area": "Shah Alam",
    "reservePrice": 270000,
    "auctionDate": "2 Jul 2026 (Thu)",
    "landArea": "—",
    "builtUp": "840 sq.ft",
    "tenure": "Freehold",
    "type": "Condo/Apartment",
    "image": "https://drive.google.com/thumbnail?id=12j2EGNvLei6cx_gOuwmLXGyoQ_z9v99s&sz=w800"
  },
  {
    "id": "30",
    "title": "1 Storey Terrace House",
    "address": "No. 16, Jalan Mutiara 10, Taman Dusun Nanding, 43100 Hulu Langat, Selangor",
    "postcode": "43100",
    "state": "Selangor",
    "area": "Hulu Langat",
    "reservePrice": 320000,
    "auctionDate": "2 Jul 2026 (Thu)",
    "landArea": "—",
    "builtUp": "033 sq.ft",
    "tenure": "Freehold",
    "type": "Terrace",
    "image": "https://drive.google.com/thumbnail?id=10wiTxzQQJAXgXPsIhV3eYgXBMZ-ri6Ea&sz=w800"
  },
  {
    "id": "31",
    "title": "3 Storey Semi Detached House",
    "address": "No. 65, Jalan Beverly Heights 2A, Beverly Heights, 68000 Ampang, Selangor",
    "postcode": "68000",
    "state": "Selangor",
    "area": "Ampang",
    "reservePrice": 1620000,
    "auctionDate": "2 Jul 2026 (Thu)",
    "landArea": "—",
    "builtUp": "601 sq.ft",
    "tenure": "Freehold",
    "type": "Terrace",
    "image": "https://drive.google.com/thumbnail?id=15Nmj2Tn1hlB_AcW3JlWIm17kVDt8vaK4&sz=w800"
  },
  {
    "id": "32",
    "title": "2 Storey Terrace House",
    "address": "No. 15, Jalan SPM 7, Taman Sri Putramas, 47000 Sungai Buloh, Selangor",
    "postcode": "47000",
    "state": "Selangor",
    "area": "Sungai Buloh",
    "reservePrice": 502200,
    "auctionDate": "2 Jul 2026 (Thu)",
    "landArea": "—",
    "builtUp": "249 sq.ft",
    "tenure": "Freehold",
    "type": "Terrace",
    "image": "https://drive.google.com/thumbnail?id=1Pps405DONJePYZpPh9yMS8M5Szxzs54y&sz=w800"
  },
  {
    "id": "33",
    "title": "2 Storey Terrace House",
    "address": "No. 1, Jalan Cempaka Lui 1, Taman Cempaka Lui, 43100 Hulu Langat, Selangor",
    "postcode": "43100",
    "state": "Selangor",
    "area": "Hulu Langat",
    "reservePrice": 840000,
    "auctionDate": "2 Jul 2026 (Thu)",
    "landArea": "—",
    "builtUp": "—",
    "tenure": "Freehold",
    "type": "Terrace",
    "image": "https://drive.google.com/thumbnail?id=104bcVDS74OoUSOTThPTa4VGu6m1LsPwW&sz=w800"
  },
  {
    "id": "34",
    "title": "2 Storey Factory",
    "address": "No. 7, Jalan Perindustrian SIS 3, Taman Perindustrian SIS 228, 43700 Beranang, Selangor",
    "postcode": "43700",
    "state": "Selangor",
    "area": "Beranang",
    "reservePrice": 2550000,
    "auctionDate": "2 Jul 2026 (Thu)",
    "landArea": "—",
    "builtUp": "431 sq.ft",
    "tenure": "Freehold",
    "type": "Terrace",
    "image": "https://drive.google.com/thumbnail?id=1sDLRARAff9BSoHoxfBdMiVG56vWwjEU5&sz=w800"
  },
  {
    "id": "35",
    "title": "2 Storey Terrace House",
    "address": "No. 16, Jalan TSJ 18, Taman Sri Jelok, 43000 Kajang, Selangor",
    "postcode": "43000",
    "state": "Selangor",
    "area": "Kajang",
    "reservePrice": 364500,
    "auctionDate": "2 Jul 2026 (Thu)",
    "landArea": "—",
    "builtUp": "539 sq.ft",
    "tenure": "Freehold",
    "type": "Terrace",
    "image": "https://drive.google.com/thumbnail?id=1OApFvPXHUjVuLNRp6UqhGEbW-8td0BUo&sz=w800"
  },
  {
    "id": "37",
    "title": "Agricultural Land",
    "address": "Lot 1205 (GM 4014), Mukim Of Ulu Langat, District Of Ulu Langat, Selangor",
    "postcode": "",
    "state": "Selangor",
    "area": "District Of Ulu Langat",
    "reservePrice": 1350000,
    "auctionDate": "2 Jul 2026 (Thu)",
    "landArea": "—",
    "builtUp": "—",
    "tenure": "Freehold",
    "type": "Land",
    "image": "https://drive.google.com/thumbnail?id=1Oi-kzlexZdLO_O1i1X_BexcWgrjEUS5n&sz=w800"
  },
  {
    "id": "43",
    "title": "2.5 Storey Semi Detached House",
    "address": "No. 321A, Jalan Puncak Saujana 3/2, Seksyen 3, Taman Puncak Saujana, 43000 Kajang, Selangor",
    "postcode": "43000",
    "state": "Selangor",
    "area": "Kajang",
    "reservePrice": 932974.2,
    "auctionDate": "6 Jul 2026 (Mon)",
    "landArea": "—",
    "builtUp": "821 sq.ft",
    "tenure": "Freehold",
    "type": "Terrace",
    "image": "https://drive.google.com/thumbnail?id=1Co-dhrWsoYhSymMf3JIeVR8J3tG2gy_9&sz=w800"
  },
  {
    "id": "44",
    "title": "Flat",
    "address": "Unit No. P3-A-05-25, Blok A, Off Jalan Sepakat Indah 3, Taman Sepakat Indah, Sungai Chua, 43000 Kajang, Selangor",
    "postcode": "43000",
    "state": "Selangor",
    "area": "Kajang",
    "reservePrice": 82674,
    "auctionDate": "6 Jul 2026 (Mon)",
    "landArea": "—",
    "builtUp": "710 sq.ft",
    "tenure": "Freehold",
    "type": "Condo/Apartment",
    "image": "https://drive.google.com/thumbnail?id=1yy_87PnfNnB3D0pS0y1DlTM409FxPmxM&sz=w800"
  },
  {
    "id": "45",
    "title": "2 Storey Detached House",
    "address": "No. 45, Jalan Desa 6/8, Bandar Country Homes, 48000 Rawang, Selangor",
    "postcode": "48000",
    "state": "Selangor",
    "area": "Rawang",
    "reservePrice": 688500,
    "auctionDate": "6 Jul 2026 (Mon)",
    "landArea": "—",
    "builtUp": "000 sq.ft",
    "tenure": "Freehold",
    "type": "Terrace",
    "image": "https://drive.google.com/thumbnail?id=1qD9if-mvzTe0eoGnXiy0gihkDFIarLuU&sz=w800"
  },
  {
    "id": "46",
    "title": "2 Storey Terrace House",
    "address": "No. 17, Jalan Bestari 3/3, Puncak Bestari, 42300 Bandar Puncak Alam, Selangor",
    "postcode": "42300",
    "state": "Selangor",
    "area": "Bandar Puncak Alam",
    "reservePrice": 511000,
    "auctionDate": "6 Jul 2026 (Mon)",
    "landArea": "—",
    "builtUp": "379 sq.ft",
    "tenure": "Freehold",
    "type": "Terrace",
    "image": "https://drive.google.com/thumbnail?id=1jHusB6jrHIadzeBjPCAT1Z8mfwHWWPMD&sz=w800"
  },
  {
    "id": "47",
    "title": "Apartment",
    "address": "Unit No. 3-108, Blok 3, Apartment Kenanga, Bandar Baru Selayang, 68100 Batu Caves, Selangor",
    "postcode": "68100",
    "state": "Selangor",
    "area": "Batu Caves",
    "reservePrice": 138000,
    "auctionDate": "6 Jul 2026 (Mon)",
    "landArea": "—",
    "builtUp": "732 sq.ft",
    "tenure": "Freehold",
    "type": "Condo/Apartment",
    "image": "https://drive.google.com/thumbnail?id=1OWQePnWarg3wwigAurlx1rpFnxQ7YYi5&sz=w800"
  },
  {
    "id": "48",
    "title": "2 Storey Terrace House",
    "address": "No. 17, Jalan Merbau, Taman Banting Baru, 42700 Banting, Selangor",
    "postcode": "42700",
    "state": "Selangor",
    "area": "Banting",
    "reservePrice": 405000,
    "auctionDate": "6 Jul 2026 (Mon)",
    "landArea": "—",
    "builtUp": "399 sq.ft",
    "tenure": "Freehold",
    "type": "Terrace",
    "image": "https://drive.google.com/thumbnail?id=1ulmtT3Cb6qCXiH6-XnQfYeKoMhzEDlEj&sz=w800"
  },
  {
    "id": "49",
    "title": "Duplex Condominium",
    "address": "Unit No. A3-11-8, Cyberia Smarthomes A, Cyberia, Cyber 11, 63000 Cyberjaya, Selangor",
    "postcode": "63000",
    "state": "Selangor",
    "area": "Cyberjaya",
    "reservePrice": 360000,
    "auctionDate": "6 Jul 2026 (Mon)",
    "landArea": "—",
    "builtUp": "088 sq.ft",
    "tenure": "Freehold",
    "type": "Condo/Apartment",
    "image": "https://drive.google.com/thumbnail?id=1Y7g1YmeesvTNGKUbNlxhud-Wl6LPPrZu&sz=w800"
  },
  {
    "id": "50",
    "title": "2 Storey Terrace House",
    "address": "No. 48, Jalan RP 4/12, Taman Rawang Perdana, 48000 Rawang, Selangor",
    "postcode": "48000",
    "state": "Selangor",
    "area": "Rawang",
    "reservePrice": 540000,
    "auctionDate": "6 Jul 2026 (Mon)",
    "landArea": "—",
    "builtUp": "295 sq.ft",
    "tenure": "Freehold",
    "type": "Terrace",
    "image": "https://drive.google.com/thumbnail?id=1-IvfyzdehZzMpI7-oPvC0ZICighe5cgv&sz=w800"
  },
  {
    "id": "53",
    "title": "Flat",
    "address": "Unit No. 10-6-08, Pangsapuri Utarid Subang, No. 1, Jalan Utarid U5/2, Seksyen U5, 40150 Shah Alam, Selangor",
    "postcode": "40150",
    "state": "Selangor",
    "area": "Shah Alam",
    "reservePrice": 108000,
    "auctionDate": "6 Jul 2026 (Mon)",
    "landArea": "—",
    "builtUp": "667 sq.ft",
    "tenure": "Freehold",
    "type": "Condo/Apartment",
    "image": "https://drive.google.com/thumbnail?id=1EFAE6vlI0gdUXmdmepnR77E_uz43DWro&sz=w800"
  },
  {
    "id": "80",
    "title": "SOHO",
    "address": "Unit No. B-12-12, 12th Floor, Block B, Kiara Plaza, Jalan Semenyih, 43500 Semenyih, Selangor",
    "postcode": "43500",
    "state": "Selangor",
    "area": "Semenyih",
    "reservePrice": 160000,
    "auctionDate": "7 Jul 2026 (Tue)",
    "landArea": "—",
    "builtUp": "476 sq.ft",
    "tenure": "Freehold",
    "type": "Terrace",
    "image": "https://drive.google.com/thumbnail?id=1M-Qg5BJ52E_--kKxvXKUFFpFDeFQsB1Q&sz=w800"
  },
  {
    "id": "84",
    "title": "Apartment",
    "address": "Unit No. 504, Pangsapuri Bukit Rawang Jaya 2, Jalan B.R.J.D/3, Taman Bukit Rawang Jaya 2, 48000 Rawang, Selangor",
    "postcode": "48000",
    "state": "Selangor",
    "area": "Rawang",
    "reservePrice": 38421,
    "auctionDate": "8 Jul 2026 (Wed)",
    "landArea": "—",
    "builtUp": "872 sq.ft",
    "tenure": "Freehold",
    "type": "Condo/Apartment",
    "image": "https://drive.google.com/thumbnail?id=1narX_aw2X7KCRB-Q0V_wxTB9bwEblt7k&sz=w800"
  },
  {
    "id": "99",
    "title": "Apartment",
    "address": "Unit No. A-4-13, 4th Floor, Block A, Pangsapuri Kenanga, Jalan TBK 1/10, Taman Bukit Kinrara, 47100 Puchong, Selangor",
    "postcode": "47100",
    "state": "Selangor",
    "area": "Puchong",
    "reservePrice": 170000,
    "auctionDate": "8 Jul 2026 (Wed)",
    "landArea": "—",
    "builtUp": "775 sq.ft",
    "tenure": "Freehold",
    "type": "Condo/Apartment",
    "image": "https://drive.google.com/thumbnail?id=1OWQePnWarg3wwigAurlx1rpFnxQ7YYi5&sz=w800"
  },
  {
    "id": "123",
    "title": "Apartment",
    "address": "Unit No. B-10-03, Block B, Impian Baiduri Apartment, No. 6, Jalan 22A, Section 51A, 46100 Petaling Jaya, Selangor",
    "postcode": "46100",
    "state": "Selangor",
    "area": "Petaling Jaya",
    "reservePrice": 150000,
    "auctionDate": "8 Jul 2026 (Wed)",
    "landArea": "—",
    "builtUp": "646 sq.ft",
    "tenure": "Freehold",
    "type": "Condo/Apartment",
    "image": "https://drive.google.com/thumbnail?id=1ieWtSixEhr0RWjhEH8fWoqqjWxgsTSk4&sz=w800"
  },
  {
    "id": "128",
    "title": "Office Unit",
    "address": "Unit No. C-01-07, Block C, Sfera Residensi, Jalan Atmosphere Utama 1, Bandar Putra Permai, 43300 Seri Kembangan, Selangor",
    "postcode": "43300",
    "state": "Selangor",
    "area": "Seri Kembangan",
    "reservePrice": 1200000,
    "auctionDate": "8 Jul 2026 (Wed)",
    "landArea": "—",
    "builtUp": "823 sq.ft",
    "tenure": "Freehold",
    "type": "Commercial",
    "image": "https://drive.google.com/thumbnail?id=1d_kfRcAXQRY8mtdkkVFFJ0PzqQJFEcnB&sz=w800"
  },
  {
    "id": "129",
    "title": "SOHO",
    "address": "Unit No. 20-18, Residensi 280, 1KM Lebuhraya Selayang-Kepong, 68100 Batu Caves, Selangor",
    "postcode": "68100",
    "state": "Selangor",
    "area": "Batu Caves",
    "reservePrice": 296000,
    "auctionDate": "8 Jul 2026 (Wed)",
    "landArea": "—",
    "builtUp": "840 sq.ft",
    "tenure": "Freehold",
    "type": "Terrace",
    "image": "https://drive.google.com/thumbnail?id=10wSucDVtCeG_VDpidPhgey34RvBtWCkY&sz=w800"
  },
  {
    "id": "144",
    "title": "Apartment",
    "address": "Unit No. B-05-01, Block B, Impian Baiduri, No. 6, Jalan 224, Seksyen 51A, 46150 Petaling Jaya, Selangor",
    "postcode": "46100",
    "state": "Selangor",
    "area": "Petaling Jaya",
    "reservePrice": 108000,
    "auctionDate": "9 Jul 2026 (Thu)",
    "landArea": "—",
    "builtUp": "646 sq.ft",
    "tenure": "Freehold",
    "type": "Condo/Apartment",
    "image": "https://drive.google.com/thumbnail?id=1ieWtSixEhr0RWjhEH8fWoqqjWxgsTSk4&sz=w800"
  },
  {
    "id": "146",
    "title": "Apartment",
    "address": "Unit No. A-17-04, Block A, Mentari Court, Jalan PJS 8/9, Taman Seri Mentari, 46150 Petaling Jaya, Selangor",
    "postcode": "46150",
    "state": "Selangor",
    "area": "Petaling Jaya",
    "reservePrice": 218700,
    "auctionDate": "9 Jul 2026 (Thu)",
    "landArea": "—",
    "builtUp": "775 sq.ft",
    "tenure": "Freehold",
    "type": "Condo/Apartment",
    "image": "https://drive.google.com/thumbnail?id=1h_S2rACsIrMiq1qCKRTOdLOAStNcGY3G&sz=w800"
  },
  {
    "id": "151",
    "title": "3 Storey Detached House",
    "address": "Lot 71 (Blok J), Taman Rawang Perdana, 48000 Rawang, Selangor",
    "postcode": "48000",
    "state": "Selangor",
    "area": "Rawang",
    "reservePrice": 2500000,
    "auctionDate": "9 Jul 2026 (Thu)",
    "landArea": "—",
    "builtUp": "213 sq.ft",
    "tenure": "Freehold",
    "type": "Terrace",
    "image": "https://drive.google.com/thumbnail?id=1-IvfyzdehZzMpI7-oPvC0ZICighe5cgv&sz=w800"
  },
  {
    "id": "153",
    "title": "1 Storey Terrace House",
    "address": "No. 14, Lorong Murni 4, Taman Murni, 45500 Tanjung Karang, Selangor",
    "postcode": "45500",
    "state": "Selangor",
    "area": "Tanjung Karang",
    "reservePrice": 207000,
    "auctionDate": "9 Jul 2026 (Thu)",
    "landArea": "—",
    "builtUp": "572 sq.ft",
    "tenure": "Freehold",
    "type": "Terrace",
    "image": "https://drive.google.com/thumbnail?id=1991veth9Dz1vWjz12x4KiDjNqLinW3lC&sz=w800"
  },
  {
    "id": "154",
    "title": "Small Office Flexible Office (SOFO)",
    "address": "Unit No. 12-22, Suria Jaya, Jalan Padang Jawa, Seksyen 16, 40200 Shah Alam, Selangor",
    "postcode": "40200",
    "state": "Selangor",
    "area": "Shah Alam",
    "reservePrice": 183708,
    "auctionDate": "9 Jul 2026 (Thu)",
    "landArea": "—",
    "builtUp": "420 sq.ft",
    "tenure": "Freehold",
    "type": "Commercial",
    "image": "https://drive.google.com/thumbnail?id=1uAoYjNFOTJTZDKUxxU-y7vu2sfa4Fr9i&sz=w800"
  },
  {
    "id": "164",
    "title": "Service Apartment",
    "address": "Unit No. H-10-18, BSP 21, Persiaran Saujana Putra Utama, Bandar Saujana Putra, 42610 Jenjarom, Selangor",
    "postcode": "42610",
    "state": "Selangor",
    "area": "Jenjarom",
    "reservePrice": 450000,
    "auctionDate": "9 Jul 2026 (Thu)",
    "landArea": "—",
    "builtUp": "259 sq.ft",
    "tenure": "Freehold",
    "type": "Condo/Apartment",
    "image": "https://drive.google.com/thumbnail?id=1dPEQ9tNLC2tw29X8XafaXYwgR81npvCg&sz=w800"
  },
  {
    "id": "184",
    "title": "2 Storey Terrace House",
    "address": "No. 27, Jalan Irama 1, Irama Perdana, LBS Alam Perdana, 42300 Bandar Puncak Alam, Selangor",
    "postcode": "42300",
    "state": "Selangor",
    "area": "Bandar Puncak Alam",
    "reservePrice": 660000,
    "auctionDate": "9 Jul 2026 (Thu)",
    "landArea": "—",
    "builtUp": "486 sq.ft",
    "tenure": "Freehold",
    "type": "Terrace",
    "image": "https://drive.google.com/thumbnail?id=1m5iJV2IV_s1lgykwg-Xc0aA5gq37yTRk&sz=w800"
  },
  {
    "id": "187",
    "title": "2 Storey Terrace House",
    "address": "No. 45A, Jalan Puncak Saujana 5/2C, Taman Puncak Saujana, Seksyen 5, 43000 Kajang, Selangor",
    "postcode": "43000",
    "state": "Selangor",
    "area": "Kajang",
    "reservePrice": 800000,
    "auctionDate": "9 Jul 2026 (Thu)",
    "landArea": "—",
    "builtUp": "475 sq.ft",
    "tenure": "Freehold",
    "type": "Terrace",
    "image": "https://drive.google.com/thumbnail?id=1HA7ob6kncprEsR3NMwNadmsece9q4psj&sz=w800"
  },
  {
    "id": "195",
    "title": "Service Apartment",
    "address": "Unit No. RS-38-03, Residential Suites Sunsuria Forum, Jalan Setia Dagang AL U13/AL, Seksyen U13, Setia Alam, 40170 Shah Alam, Selangor",
    "postcode": "40170",
    "state": "Selangor",
    "area": "Shah Alam",
    "reservePrice": 380000,
    "auctionDate": "9 Jul 2026 (Thu)",
    "landArea": "—",
    "builtUp": "883 sq.ft",
    "tenure": "Freehold",
    "type": "Condo/Apartment",
    "image": "https://drive.google.com/thumbnail?id=1DGkvEzB7Ojc89F7OnObUmWNlYQcjUNNu&sz=w800"
  },
  {
    "id": "203",
    "title": "Service Apartment",
    "address": "Unit No. A-41-05, Menara Inspirasi, No. 30, Jalan 1/65A, Off Jalan Tun Razak, 50400, Kuala Lumpur",
    "postcode": "50400",
    "state": "Kuala Lumpur",
    "area": "Kuala Lumpur",
    "reservePrice": 940000,
    "auctionDate": "9 Jul 2026 (Thu)",
    "landArea": "—",
    "builtUp": "345 sq.ft",
    "tenure": "Freehold",
    "type": "Condo/Apartment",
    "image": "https://drive.google.com/thumbnail?id=14FNQvHVcu5h9xkpbE0-TLtF04qhC5UcO&sz=w800"
  },
  {
    "id": "208",
    "title": "Retail Lot",
    "address": "Unit No. 5-23, Kenanga Wholesale City, Jalan Gelugor, 55200, Kuala Lumpur",
    "postcode": "55200",
    "state": "Kuala Lumpur",
    "area": "Kuala Lumpur",
    "reservePrice": 693000,
    "auctionDate": "9 Jul 2026 (Thu)",
    "landArea": "—",
    "builtUp": "548 sq.ft",
    "tenure": "Freehold",
    "type": "Commercial",
    "image": "https://drive.google.com/thumbnail?id=1NfE4fqlSgxhb37KvUrnkV9ZWkKMExZ0W&sz=w800"
  },
  {
    "id": "223",
    "title": "Villa Angsana Condominium",
    "address": "Unit No. C-21-1, Block C, Villa Angsana Condominium, No. 56, Jalan Krian, Taman Rainbow, 51100, Kuala Lumpur",
    "postcode": "51100",
    "state": "Kuala Lumpur",
    "area": "Kuala Lumpur",
    "reservePrice": 329000,
    "auctionDate": "9 Jul 2026 (Thu)",
    "landArea": "—",
    "builtUp": "324 sq.ft",
    "tenure": "Freehold",
    "type": "Condo/Apartment",
    "image": "https://drive.google.com/thumbnail?id=1f_MzjYvTMRRhWl_j1KqNUr7svjL1lS3R&sz=w800"
  },
  {
    "id": "232",
    "title": "Office Lot",
    "address": "Unit No. L12A-17, Wangsa 118, No. 8, Jalan Wangsa Delima, Wangsa Maju 53300, Kuala Lumpur",
    "postcode": "53300",
    "state": "Kuala Lumpur",
    "area": "Wangsa Maju",
    "reservePrice": 380000,
    "auctionDate": "9 Jul 2026 (Thu)",
    "landArea": "—",
    "builtUp": "850 sq.ft",
    "tenure": "Freehold",
    "type": "Commercial",
    "image": "https://drive.google.com/thumbnail?id=1YkJ5q_-1yCeFvDF-1s_smlQxH6rgIb0s&sz=w800"
  },
  {
    "id": "233",
    "title": "Service Apartment",
    "address": "Unit No. A1-10-3A, Block A1, Parklane OUG Service Apartment, No. 1, Jalan 1/52, Taman OUG Parklane, 58200, Kuala Lumpur",
    "postcode": "58200",
    "state": "Kuala Lumpur",
    "area": "Kuala Lumpur",
    "reservePrice": 237600,
    "auctionDate": "9 Jul 2026 (Thu)",
    "landArea": "—",
    "builtUp": "958 sq.ft",
    "tenure": "Freehold",
    "type": "Condo/Apartment",
    "image": "https://drive.google.com/thumbnail?id=1IvGs39bwau3xPXX0d75-6qmo-9vBgTll&sz=w800"
  },
  {
    "id": "234",
    "title": "Service Apartment",
    "address": "Unit No. A2-28-3A, Parklane OUG Service Apartment, Blok A2, No. 1, Jalan 1/152, Taman OUG Parklane, 58200, Kuala Lumpur",
    "postcode": "58200",
    "state": "Kuala Lumpur",
    "area": "Kuala Lumpur",
    "reservePrice": 240000,
    "auctionDate": "9 Jul 2026 (Thu)",
    "landArea": "—",
    "builtUp": "958 sq.ft",
    "tenure": "Freehold",
    "type": "Condo/Apartment",
    "image": "https://drive.google.com/thumbnail?id=1IvGs39bwau3xPXX0d75-6qmo-9vBgTll&sz=w800"
  },
  {
    "id": "235",
    "title": "Service Apartment",
    "address": "Unit No. B1-20-7, Block B1, Parklane OUG Service Apartment, No. 1, Jalan 1/52, Taman OUG Parklane, 58200, Kuala Lumpur",
    "postcode": "58200",
    "state": "Kuala Lumpur",
    "area": "Kuala Lumpur",
    "reservePrice": 264000,
    "auctionDate": "9 Jul 2026 (Thu)",
    "landArea": "—",
    "builtUp": "958 sq.ft",
    "tenure": "Freehold",
    "type": "Condo/Apartment",
    "image": "https://drive.google.com/thumbnail?id=1IvGs39bwau3xPXX0d75-6qmo-9vBgTll&sz=w800"
  },
  {
    "id": "286",
    "title": "Apartment",
    "address": "Unit No. 1-3-11, Block 1, Kondominium Puncak Seri Kelana, Jalan PJU 1A/46, 47301 Petaling Jaya, Selangor",
    "postcode": "47301",
    "state": "Selangor",
    "area": "Petaling Jaya",
    "reservePrice": 260820,
    "auctionDate": "14 Jul 2026 (Tue)",
    "landArea": "—",
    "builtUp": "259 sq.ft",
    "tenure": "Freehold",
    "type": "Condo/Apartment",
    "image": "https://drive.google.com/thumbnail?id=1lxlO7kq8ogC3l-BbenV-dfXfWM1_bjxs&sz=w800"
  },
  {
    "id": "306",
    "title": "Service Apartment",
    "address": "Unit No. B-20-2, Pangsapuri Suria Perdana, Taman Serdang Perdana Sek 4, 43300 Seri Kembangan, Selangor",
    "postcode": "43300",
    "state": "Selangor",
    "area": "Seri Kembangan",
    "reservePrice": 300000,
    "auctionDate": "14 Jul 2026 (Tue)",
    "landArea": "—",
    "builtUp": "195 sq.ft",
    "tenure": "Freehold",
    "type": "Condo/Apartment",
    "image": "https://drive.google.com/thumbnail?id=1qxB-foyWgwSb5Jq7gTW3Sy0ytaYXF3iB&sz=w800"
  },
  {
    "id": "308",
    "title": "Apartment",
    "address": "Unit No. E-15-19, Blok E, Mentari Court, Jalan PJS 8/9, Taman Seri Mentari, 46150 Petaling Jaya, Selangor",
    "postcode": "46150",
    "state": "Selangor",
    "area": "Petaling Jaya",
    "reservePrice": 250000,
    "auctionDate": "14 Jul 2026 (Tue)",
    "landArea": "—",
    "builtUp": "775 sq.ft",
    "tenure": "Freehold",
    "type": "Condo/Apartment",
    "image": "https://drive.google.com/thumbnail?id=1h_S2rACsIrMiq1qCKRTOdLOAStNcGY3G&sz=w800"
  },
  {
    "id": "309",
    "title": "Apartment",
    "address": "Unit No. B-16-18, Blok B, Mentari Court, Jalan PJS 8/9, Taman Seri Mentari, 46150 Petaling Jaya, Selangor",
    "postcode": "46150",
    "state": "Selangor",
    "area": "Petaling Jaya",
    "reservePrice": 300000,
    "auctionDate": "14 Jul 2026 (Tue)",
    "landArea": "—",
    "builtUp": "775 sq.ft",
    "tenure": "Freehold",
    "type": "Condo/Apartment",
    "image": "https://drive.google.com/thumbnail?id=1h_S2rACsIrMiq1qCKRTOdLOAStNcGY3G&sz=w800"
  },
  {
    "id": "323",
    "title": "Apartment",
    "address": "Unit No. B3-41-09, Residensi PR1MA Alam Damai, Persiaran Bestari, Alam Damai, 56000, Kuala Lumpur",
    "postcode": "56000",
    "state": "Kuala Lumpur",
    "area": "Kuala Lumpur",
    "reservePrice": 269700,
    "auctionDate": "14 Jul 2026 (Tue)",
    "landArea": "—",
    "builtUp": "990 sq.ft",
    "tenure": "Freehold",
    "type": "Condo/Apartment",
    "image": "https://drive.google.com/thumbnail?id=1cVC8feyuqT6bv3Ox9QQj3N_olhUPIDJ2&sz=w800"
  },
  {
    "id": "350",
    "title": "Condominium",
    "address": "Unit No. A1-3-3, Cyberia Smarthomes A Cyberia, Cyber 11, 63000 Cyberjaya, Selangor",
    "postcode": "63000",
    "state": "Selangor",
    "area": "Cyberjaya",
    "reservePrice": 207000,
    "auctionDate": "15 Jul 2026 (Wed)",
    "landArea": "—",
    "builtUp": "001 sq.ft",
    "tenure": "Freehold",
    "type": "Condo/Apartment",
    "image": "https://drive.google.com/thumbnail?id=1Y7g1YmeesvTNGKUbNlxhud-Wl6LPPrZu&sz=w800"
  },
  {
    "id": "351",
    "title": "Condominium",
    "address": "Unit No. A-11-03, Blok A, Jalan KPB 18, Windows On The Park, Bandar Tun Hussein Onn, 43200 Cheras, Selangor",
    "postcode": "43200",
    "state": "Selangor",
    "area": "Cheras",
    "reservePrice": 780000,
    "auctionDate": "15 Jul 2026 (Wed)",
    "landArea": "—",
    "builtUp": "024 sq.ft",
    "tenure": "Freehold",
    "type": "Condo/Apartment",
    "image": "https://drive.google.com/thumbnail?id=18xTLwokTZneTpnMY1ggs1krLFmXu1D9b&sz=w800"
  },
  {
    "id": "358",
    "title": "Condominium",
    "address": "Unit No. D-13A-02, Block D-Liana 2, Residensi Vyne Sungai Besi, No. 8, Jalan 1/108D, Sungai Besi, 57100, Kuala Lumpur",
    "postcode": "57100",
    "state": "Kuala Lumpur",
    "area": "Kuala Lumpur",
    "reservePrice": 520000,
    "auctionDate": "15 Jul 2026 (Wed)",
    "landArea": "—",
    "builtUp": "087 sq.ft",
    "tenure": "Freehold",
    "type": "Condo/Apartment",
    "image": "https://drive.google.com/thumbnail?id=1_0sTXy7Ntsa2-53TVXq9bYYr4SM3jGI7&sz=w800"
  },
  {
    "id": "361",
    "title": "Apartment",
    "address": "Unit No. D-23A-05, Residensi Vyne, Jalan 1/108D, Sungai Besi, 57100, Kuala Lumpur",
    "postcode": "57100",
    "state": "Kuala Lumpur",
    "area": "Kuala Lumpur",
    "reservePrice": 510300,
    "auctionDate": "15 Jul 2026 (Wed)",
    "landArea": "—",
    "builtUp": "237 sq.ft",
    "tenure": "Freehold",
    "type": "Condo/Apartment",
    "image": "https://drive.google.com/thumbnail?id=1_0sTXy7Ntsa2-53TVXq9bYYr4SM3jGI7&sz=w800"
  },
  {
    "id": "374",
    "title": "Apartment",
    "address": "Unit No. 2-6-2, Block 2, Pangsapuri Seroja, No. 2, Jalan Setia Murni U13/50, Setia Alam, Seksyen U13, 40170 Shah Alam, Selangor",
    "postcode": "40170",
    "state": "Selangor",
    "area": "Shah Alam",
    "reservePrice": 114000,
    "auctionDate": "16 Jul 2026 (Thu)",
    "landArea": "—",
    "builtUp": "667 sq.ft",
    "tenure": "Freehold",
    "type": "Condo/Apartment",
    "image": "https://drive.google.com/thumbnail?id=12j2EGNvLei6cx_gOuwmLXGyoQ_z9v99s&sz=w800"
  },
  {
    "id": "384",
    "title": "Apartment",
    "address": "Unit No. A-17-05, Block A, Mentari Court, Jalan PJS 8/9, Taman Seri Mentari, 46150 Petaling Jaya, Selangor",
    "postcode": "46150",
    "state": "Selangor",
    "area": "Petaling Jaya",
    "reservePrice": 226800,
    "auctionDate": "16 Jul 2026 (Thu)",
    "landArea": "—",
    "builtUp": "775 sq.ft",
    "tenure": "Freehold",
    "type": "Condo/Apartment",
    "image": "https://drive.google.com/thumbnail?id=1h_S2rACsIrMiq1qCKRTOdLOAStNcGY3G&sz=w800"
  },
  {
    "id": "388",
    "title": "Flat",
    "address": "Unit No. B10-1-20, Block 10, Jalan PJS 2B/1, Desa Mentari 2, 46150 Petaling Jaya, Selangor",
    "postcode": "46150",
    "state": "Selangor",
    "area": "Petaling Jaya",
    "reservePrice": 160000,
    "auctionDate": "16 Jul 2026 (Thu)",
    "landArea": "—",
    "builtUp": "657 sq.ft",
    "tenure": "Freehold",
    "type": "Condo/Apartment",
    "image": "https://drive.google.com/thumbnail?id=1QVQstc1-g2zezqgIPufuYK7AU_8z_sCW&sz=w800"
  },
  {
    "id": "410",
    "title": "Condominium",
    "address": "Unit No. A-05-08, Block A, Residensi Sembilan Cheras, Jalan Suria Residen, 43200 Cheras, Selangor",
    "postcode": "43200",
    "state": "Selangor",
    "area": "Cheras",
    "reservePrice": 670000,
    "auctionDate": "16 Jul 2026 (Thu)",
    "landArea": "—",
    "builtUp": "496 sq.ft",
    "tenure": "Freehold",
    "type": "Condo/Apartment",
    "image": "https://drive.google.com/thumbnail?id=1Yxyn3IrlYKNyS5e0y26jVGWAgBrbEZjU&sz=w800"
  },
  {
    "id": "414",
    "title": "Duplex Service Apartment",
    "address": "Unit No. A-43-06, 43rd Floor, Menara Inspirasi (Expressionz Professional Suites @ Tun Razak), No. 30, Jalan 1/65A, Off Jalan Tun Razak, 50400, Kuala Lumpur",
    "postcode": "50400",
    "state": "Kuala Lumpur",
    "area": "Kuala Lumpur",
    "reservePrice": 777600,
    "auctionDate": "16 Jul 2026 (Thu)",
    "landArea": "—",
    "builtUp": "410 sq.ft",
    "tenure": "Freehold",
    "type": "Condo/Apartment",
    "image": "https://drive.google.com/thumbnail?id=14FNQvHVcu5h9xkpbE0-TLtF04qhC5UcO&sz=w800"
  },
  {
    "id": "418",
    "title": "Apartment",
    "address": "Unit No. B4-08-02, Residensi PR1MA Alam Damai, Persiaran Bistari, Alam Damai, 56000, Kuala Lumpur",
    "postcode": "56000",
    "state": "Kuala Lumpur",
    "area": "Kuala Lumpur",
    "reservePrice": 284000,
    "auctionDate": "16 Jul 2026 (Thu)",
    "landArea": "—",
    "builtUp": "936 sq.ft",
    "tenure": "Freehold",
    "type": "Condo/Apartment",
    "image": "https://drive.google.com/thumbnail?id=1cVC8feyuqT6bv3Ox9QQj3N_olhUPIDJ2&sz=w800"
  },
  {
    "id": "446",
    "title": "Condominium",
    "address": "Unit No. A-03A-05, 4th Floor, Block A, Residensi Sembilan Cheras, Jalan Suria Residen, 43200 Cheras, Selangor",
    "postcode": "43200",
    "state": "Selangor",
    "area": "Cheras",
    "reservePrice": 520000,
    "auctionDate": "22 Jul 2026 (Wed)",
    "landArea": "—",
    "builtUp": "119 sq.ft",
    "tenure": "Freehold",
    "type": "Condo/Apartment",
    "image": "https://drive.google.com/thumbnail?id=1Yxyn3IrlYKNyS5e0y26jVGWAgBrbEZjU&sz=w800"
  },
  {
    "id": "448",
    "title": "Apartment",
    "address": "No. G-11-04, Blok G, (On Site Is No. G-11-4, Tower G), Mentari Court, Jalan PJS 8/9, Taman Seri Mentari, 46150 Petaling Jaya, Selangor",
    "postcode": "46150",
    "state": "Selangor",
    "area": "Petaling Jaya",
    "reservePrice": 225000,
    "auctionDate": "22 Jul 2026 (Wed)",
    "landArea": "—",
    "builtUp": "775 sq.ft",
    "tenure": "Freehold",
    "type": "Condo/Apartment",
    "image": "https://drive.google.com/thumbnail?id=1h_S2rACsIrMiq1qCKRTOdLOAStNcGY3G&sz=w800"
  },
  {
    "id": "456",
    "title": "Condominium",
    "address": "Unit No. A-7-1, Kondominium Villa Angsana (Block A), Jalan Krian, Taman Rainbow, 51100, Kuala Lumpur",
    "postcode": "51100",
    "state": "Kuala Lumpur",
    "area": "Kuala Lumpur",
    "reservePrice": 288800,
    "auctionDate": "22 Jul 2026 (Wed)",
    "landArea": "—",
    "builtUp": "324 sq.ft",
    "tenure": "Freehold",
    "type": "Condo/Apartment",
    "image": "https://drive.google.com/thumbnail?id=1f_MzjYvTMRRhWl_j1KqNUr7svjL1lS3R&sz=w800"
  },
  {
    "id": "458",
    "title": "Service Apartment",
    "address": "Pangsapuri Suria Perdana (Fortune Park), Taman Serdang Perdana, Seksyen 4, 43300 Seri Kembangan, Selangor",
    "postcode": "43300",
    "state": "Selangor",
    "area": "Seri Kembangan",
    "reservePrice": 159432.3,
    "auctionDate": "23 Jul 2026 (Thu)",
    "landArea": "—",
    "builtUp": "109 sq.ft",
    "tenure": "Freehold",
    "type": "Condo/Apartment",
    "image": "https://drive.google.com/thumbnail?id=1qxB-foyWgwSb5Jq7gTW3Sy0ytaYXF3iB&sz=w800"
  },
  {
    "id": "461",
    "title": "Flat",
    "address": "Unit No. B10-16-29, Block 10, Jalan PJS 2B/1, Desa Mentari 2, 46150 Petaling Jaya, Selangor",
    "postcode": "46150",
    "state": "Selangor",
    "area": "Petaling Jaya",
    "reservePrice": 126000,
    "auctionDate": "23 Jul 2026 (Thu)",
    "landArea": "—",
    "builtUp": "657 sq.ft",
    "tenure": "Freehold",
    "type": "Condo/Apartment",
    "image": "https://drive.google.com/thumbnail?id=1QVQstc1-g2zezqgIPufuYK7AU_8z_sCW&sz=w800"
  },
  {
    "id": "477",
    "title": "Apartment",
    "address": "Residensi PR1MA Alam Damai, No. 8, Persiaran Bistari, Alam Damai, 56000, Kuala Lumpur",
    "postcode": "56000",
    "state": "Kuala Lumpur",
    "area": "Kuala Lumpur",
    "reservePrice": 247860,
    "auctionDate": "23 Jul 2026 (Thu)",
    "landArea": "—",
    "builtUp": "990 sq.ft",
    "tenure": "Freehold",
    "type": "Condo/Apartment",
    "image": "https://drive.google.com/thumbnail?id=1cVC8feyuqT6bv3Ox9QQj3N_olhUPIDJ2&sz=w800"
  },
  {
    "id": "482",
    "title": "Condominium",
    "address": "Unit No. B-05-03, Tingkat 5, Block B, Residensi Riverville, No. 6, Jalan Taman Sri Sentosa, 58000, Kuala Lumpur",
    "postcode": "58000",
    "state": "Kuala Lumpur",
    "area": "Kuala Lumpur",
    "reservePrice": 603000,
    "auctionDate": "23 Jul 2026 (Thu)",
    "landArea": "—",
    "builtUp": "120 sq.ft",
    "tenure": "Freehold",
    "type": "Condo/Apartment",
    "image": "https://drive.google.com/thumbnail?id=1TxGSoS_W1lHpItuvFVoaTmDoTc87jMY4&sz=w800"
  },
  {
    "id": "485",
    "title": "Condominium",
    "address": "Unit No. A-15-09, Block A, Residensi Sembilan Cheras, Jalan Suria Residen, 43200 Cheras, Selangor",
    "postcode": "43200",
    "state": "Selangor",
    "area": "Cheras",
    "reservePrice": 371790,
    "auctionDate": "28 Jul 2026 (Tue)",
    "landArea": "—",
    "builtUp": "502 sq.ft",
    "tenure": "Freehold",
    "type": "Condo/Apartment",
    "image": "https://drive.google.com/thumbnail?id=1Yxyn3IrlYKNyS5e0y26jVGWAgBrbEZjU&sz=w800"
  },
  {
    "id": "496",
    "title": "Service Apartment",
    "address": "Unit No. B-11-08, BSP 21, Persiaran Saujana Putra Utama, Bandar Saujana Putra, 42610 Jenjarom, Selangor",
    "postcode": "42610",
    "state": "Selangor",
    "area": "Jenjarom",
    "reservePrice": 300000,
    "auctionDate": "28 Jul 2026 (Tue)",
    "landArea": "—",
    "builtUp": "044 sq.ft",
    "tenure": "Freehold",
    "type": "Condo/Apartment",
    "image": "https://drive.google.com/thumbnail?id=1dPEQ9tNLC2tw29X8XafaXYwgR81npvCg&sz=w800"
  },
  {
    "id": "498",
    "title": "Service Apartment",
    "address": "Unit No. A-30-02, Block A, Kiara Plaza, Jalan Semenyih, 43500 Semenyih, Selangor",
    "postcode": "43500",
    "state": "Selangor",
    "area": "Semenyih",
    "reservePrice": 300000,
    "auctionDate": "28 Jul 2026 (Tue)",
    "landArea": "—",
    "builtUp": "050 sq.ft",
    "tenure": "Freehold",
    "type": "Condo/Apartment",
    "image": "https://drive.google.com/thumbnail?id=1M-Qg5BJ52E_--kKxvXKUFFpFDeFQsB1Q&sz=w800"
  },
  {
    "id": "503",
    "title": "2 Storey Terrace House",
    "address": "No. 35, Jalan Ritma 2/11, Ritma Perdana, LBS Alam Perdana, 42300 Bandar Puncak Alam, Selangor",
    "postcode": "42300",
    "state": "Selangor",
    "area": "Bandar Puncak Alam",
    "reservePrice": 500000,
    "auctionDate": "28 Jul 2026 (Tue)",
    "landArea": "—",
    "builtUp": "200 sq.ft",
    "tenure": "Freehold",
    "type": "Terrace",
    "image": "https://drive.google.com/thumbnail?id=1X5TKUkmSnIjGQeYZO8xsKP5T1prSr1OH&sz=w800"
  },
  {
    "id": "532",
    "title": "Condominium",
    "address": "Unit No. A-23A-05, Block A, Residensi Riverville, No. 6, Jalan Taman Sri Sentosa, Taman Sri Sentosa, 58000, Kuala Lumpur",
    "postcode": "58000",
    "state": "Kuala Lumpur",
    "area": "Kuala Lumpur",
    "reservePrice": 610000,
    "auctionDate": "29 Jul 2026 (Wed)",
    "landArea": "—",
    "builtUp": "216 sq.ft",
    "tenure": "Freehold",
    "type": "Condo/Apartment",
    "image": "https://drive.google.com/thumbnail?id=1TxGSoS_W1lHpItuvFVoaTmDoTc87jMY4&sz=w800"
  },
  {
    "id": "542",
    "title": "3 Storey Detached House together with a basement and swimming pool",
    "address": "No. 3, Mutiara 33, Jalan Kemuning 33/158B, Seksyen 33, Taman Kemuning Utama, 40400 Shah Alam, Selangor",
    "postcode": "40400",
    "state": "Selangor",
    "area": "Shah Alam",
    "reservePrice": 1950000,
    "auctionDate": "30 Jul 2026 (Thu)",
    "landArea": "—",
    "builtUp": "180 sq.ft",
    "tenure": "Freehold",
    "type": "Terrace",
    "image": "https://drive.google.com/thumbnail?id=1h0DKLFM6m4xcKauyKxmFTV93gH2EojRl&sz=w800"
  },
  {
    "id": "557",
    "title": "Flat",
    "address": "Unit No. 10-6-14, Tingkat 6, Block 10, Pangsapuri Utarid Subang, No. 1, Jalan Utarid U5/2, Seksyen U5, 40150 Shah Alam, Selangor",
    "postcode": "40150",
    "state": "Selangor",
    "area": "Shah Alam",
    "reservePrice": 67910,
    "auctionDate": "3 Aug 2026 (Mon)",
    "landArea": "—",
    "builtUp": "667 sq.ft",
    "tenure": "Freehold",
    "type": "Condo/Apartment",
    "image": "https://drive.google.com/thumbnail?id=1EFAE6vlI0gdUXmdmepnR77E_uz43DWro&sz=w800"
  },
  {
    "id": "566",
    "title": "Condominium",
    "address": "Unit No. A-07-10, Residensi Sembilan Cheras, Jalan Suria Residence, 43200 Cheras, Selangor",
    "postcode": "43200",
    "state": "Selangor",
    "area": "Cheras",
    "reservePrice": 560000,
    "auctionDate": "3 Aug 2026 (Mon)",
    "landArea": "—",
    "builtUp": "216 sq.ft",
    "tenure": "Freehold",
    "type": "Condo/Apartment",
    "image": "https://drive.google.com/thumbnail?id=1Yxyn3IrlYKNyS5e0y26jVGWAgBrbEZjU&sz=w800"
  },
  {
    "id": "592",
    "title": "Apartment",
    "address": "Unit No. C-8-9, Block C, Mentari Court, Jalan PJS 8/9, Taman Seri Mentari, 46150 Petaling Jaya, Selangor",
    "postcode": "46150",
    "state": "Selangor",
    "area": "Petaling Jaya",
    "reservePrice": 226800,
    "auctionDate": "6 Aug 2026 (Thu)",
    "landArea": "—",
    "builtUp": "775 sq.ft",
    "tenure": "Freehold",
    "type": "Condo/Apartment",
    "image": "https://drive.google.com/thumbnail?id=1h_S2rACsIrMiq1qCKRTOdLOAStNcGY3G&sz=w800"
  },
  {
    "id": "600",
    "title": "Condominium",
    "address": "Unit No. A-21-11, Block A, Residensi Riverville, No. 6, Jalan Taman Seri Sentosa, Taman Seri Sentosa, 58000, Kuala Lumpur",
    "postcode": "58000",
    "state": "Kuala Lumpur",
    "area": "Kuala Lumpur",
    "reservePrice": 550800,
    "auctionDate": "6 Aug 2026 (Thu)",
    "landArea": "—",
    "builtUp": "399 sq.ft",
    "tenure": "Freehold",
    "type": "Condo/Apartment",
    "image": "https://drive.google.com/thumbnail?id=1TxGSoS_W1lHpItuvFVoaTmDoTc87jMY4&sz=w800"
  },
  {
    "id": "625",
    "title": "Condominium",
    "address": "Block A, Endah Regal Condominium, Jalan 3/149E, Taman Sri Endah, 57000, Kuala Lumpur",
    "postcode": "57000",
    "state": "Kuala Lumpur",
    "area": "Kuala Lumpur",
    "reservePrice": 241000,
    "auctionDate": "12 Aug 2026 (Wed)",
    "landArea": "—",
    "builtUp": "141 sq.ft",
    "tenure": "Freehold",
    "type": "Condo/Apartment",
    "image": "https://drive.google.com/thumbnail?id=1RDJzgewGn2YhDRFxh9RFvzd55MEkRg4t&sz=w800"
  },
  {
    "id": "631",
    "title": "Condominium",
    "address": "Unit No. B-9-6, Block B, Jalan 3/149E, Endah Regal Condominium, Taman Seri Endah, 57000, Kuala Lumpur",
    "postcode": "57000",
    "state": "Kuala Lumpur",
    "area": "Kuala Lumpur",
    "reservePrice": 330000,
    "auctionDate": "12 Aug 2026 (Wed)",
    "landArea": "—",
    "builtUp": "141 sq.ft",
    "tenure": "Freehold",
    "type": "Condo/Apartment",
    "image": "https://drive.google.com/thumbnail?id=1RDJzgewGn2YhDRFxh9RFvzd55MEkRg4t&sz=w800"
  },
  {
    "id": "636",
    "title": "1 Storey Terrace House",
    "address": "No. 4, Jalan BB 4/10, Taman Banting Baru, 42700 Banting, Selangor",
    "postcode": "42700",
    "state": "Selangor",
    "area": "Banting",
    "reservePrice": 300000,
    "auctionDate": "13 Aug 2026 (Thu)",
    "landArea": "—",
    "builtUp": "302 sq.ft",
    "tenure": "Freehold",
    "type": "Terrace",
    "image": "https://drive.google.com/thumbnail?id=1ulmtT3Cb6qCXiH6-XnQfYeKoMhzEDlEj&sz=w800"
  },
  {
    "id": "656",
    "title": "Condominium",
    "address": "Unit No. B-9-2, Kondo Villa Angsana, Block B, Jalan Krian, Taman Rainbow, 51100, Kuala Lumpur",
    "postcode": "51100",
    "state": "Kuala Lumpur",
    "area": "Kuala Lumpur",
    "reservePrice": 420000,
    "auctionDate": "30 Sep 2026 (Wed)",
    "landArea": "—",
    "builtUp": "421 sq.ft",
    "tenure": "Freehold",
    "type": "Condo/Apartment",
    "image": "https://drive.google.com/thumbnail?id=1f_MzjYvTMRRhWl_j1KqNUr7svjL1lS3R&sz=w800"
  },
  {
    "id": "658",
    "title": "Service Apartment",
    "address": "Unit No. 9-10, MH Platinum Residence, Jalan Gombak Sejahtera, Off Jalan Gombak, Setapak, 53000, Kuala Lumpur",
    "postcode": "53000",
    "state": "Kuala Lumpur",
    "area": "Kuala Lumpur",
    "reservePrice": 420000,
    "auctionDate": "30 Sep 2026 (Wed)",
    "landArea": "—",
    "builtUp": "023 sq.ft",
    "tenure": "Freehold",
    "type": "Condo/Apartment",
    "image": "https://drive.google.com/thumbnail?id=1Es75GcFGRVbDuAcaC-H1kKwVI4_0ugZI&sz=w800"
  }
];

export function formatPrice(price: number): string {
  return new Intl.NumberFormat("en-MY", {
    style: "currency",
    currency: "MYR",
    maximumFractionDigits: 0,
  }).format(price);
}
